### PR TITLE
fix(Calendar): enable preview on drag move

### PR DESCRIPTION
**Pull request by mdelez**
## Types of changes

What types of changes does your code introduce?

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Description
After dragging to select a date range, the preview for the next range is not displayed unless the user moves the cursor out of the calendar and then back in (or clicks on the calendar somewhere, not necessarily a date). This change enables the preview for the next range immediately.

### CODE REVIEW

**Comment by mdelez** [comment]
oops, accidentally deleted the branch 😅

**Comment by mdelez** [comment]
@goguda, do you have a contact email? I have some ideas I'd like to discuss if you're open to it.

**Comment by goguda** [comment]
> @goguda, do you have a contact email? I have some ideas I'd like to discuss if you're open to it.

Ah, this was a good catch, thank you!

And yes, you can reach me at davidgoguen@iroomit.com :)

**Comment by goguda** [comment]
Do you have a public email address as well? I'd like to add you to the list of contributors if so!

**Pull request merged**
